version: '3'
services:
  node:
    image: node:14.18.1
    ports:
      - 3000:3000
      - 8081:8081
    user: node
    volumes:
      - ./:/app:rw
    working_dir: /app
    command: sh -c "npm i && npm run ${NPM_RUN}"

networks:
  app:
